"""
Single source of truth for all site content.
Used by generate_site.py to render all 25 HTML pages.
"""

BUSINESS = {
    "name": "Intracoastal Installs",
    "legal_name": "Intracoastal Installs LLC",
    "slogan": "Professional Dock Building, Repair, and Replacement!",
    "founder": "Mark Lipe",
    "license": "100980",
    "license_label": "NC General Contractor #100980",
    "phone_display": "(910) 612-6107",
    "phone_link": "+19106126107",
    "email": "mark@intracoastalinstalls.com",
    "address_street": "312 Olde Point Loop",
    "address_city": "Hampstead",
    "address_state": "NC",
    "address_zip": "28443",
    "lat": 34.3683,
    "lng": -77.7102,
    "hours": "Monday–Friday, 7am–5pm",
    "facebook": "https://www.facebook.com/intracoastalinstalls",
    "domain": "https://intracoastalinstalls.com",
    "last_updated": "2026-05-08",
    "canonical_sentence": (
        "Intracoastal Installs LLC is a family-owned dock and deck construction company "
        "serving Hampstead, Wilmington, and the coastal North Carolina region, "
        "specializing in floating docks, fixed piers, boat lifts, gazebos, and pilings — "
        "with NC General Contractor license #100980 and over 30 years of marine "
        "construction experience."
    ),
    "web3forms_key": "YOUR_WEB3FORMS_KEY_HERE",  # Client to replace post-launch
}

SERVICES = [
    {
        "slug": "floating-docks",
        "name": "Floating Docks",
        "h1": "Floating Docks Built to Outlast Coastal NC Salt",
        "title": "Floating Dock Builder in Coastal NC | Intracoastal Installs",
        "meta": "Family-owned floating dock builder serving Hampstead, Wilmington, and the coastal NC corridor. NC GC #100980, marine-grade lumber, stainless steel fasteners. Free written estimates.",
        "subhead": "30+ years building floating docks on the ICW with #1 marine-grade pressure-treated lumber and stainless steel fasteners.",
        "trust_pills": ["NC GC #100980", "Marine-Grade Lumber", "Stainless Fasteners"],
        "summary": "Floating docks built with #1 marine-grade lumber, stainless fasteners, and USA-made float pontoons.",
        "problem": "Standard floating docks fail in saltwater because contractors spec landside fasteners and economy lumber. After two seasons on the ICW, those decks warp, hardware corrodes, and connections loosen at the worst possible time.",
        "included": [
            "Site evaluation and tide-cycle survey",
            "CAMA / local permit consultation and submission",
            "Float pontoon selection (USA-made, polystyrene-filled)",
            "Frame construction with #1 marine-grade pressure-treated lumber",
            "Decking in pressure-treated, composite, or IPE Brazilian hardwood",
            "Stainless steel through-bolting at every connection",
            "Galvanized cleats sized to your boat",
            "Articulating gangway with handrails sized to your shoreline",
            "Anchor pilings driven to engineer-recommended depth",
            "Final inspection walk-through with you",
        ],
        "process": [
            ("Free site visit", "We measure tide swing, check substrate, and walk the shoreline with you."),
            ("Permit-aware design", "Sketch with float footprint, gangway run, piling locations, and decking choice."),
            ("Written estimate", "Itemized materials and a 1–3 week installation window."),
            ("Permit submission", "CAMA, county, and Town as required — we handle the paperwork."),
            ("In-house installation", "Our crew builds. No subcontractors."),
            ("Final walk-through", "Documented inspection with you onboard."),
        ],
        "materials": [
            "#1 marine-grade pressure-treated southern yellow pine",
            "316 stainless steel through-bolts and nuts (not 304, not galvanized for connections)",
            "USA-made polystyrene-filled float pontoons",
            "Galvanized cleats and chocks sized to your boat displacement",
            "Optional IPE Brazilian hardwood decking — 50+ year unfinished service life",
        ],
        "warranty": "Workmanship guaranteed to endure normal coastal NC service conditions. Manufacturer warranties on USA-made float pontoons and hardware pass through to you.",
        "timeline": "1–3 weeks from permit approval to inspection.",
        "faqs": [
            ("How much does a floating dock cost in coastal NC?",
             "Pricing depends on size, decking material, gangway length, and permit complexity. A typical residential floating dock with a 4×20 float and a 4×16 gangway runs in the mid-five-figure range; IPE decking and longer gangways increase that. We provide a free written estimate after a site visit."),
            ("Do I need a CAMA permit for a floating dock in coastal NC?",
             "In almost every coastal NC location, yes. CAMA Major or General Permit jurisdiction depends on the size and water-frontage type. We handle the permit submission as part of our process."),
            ("How long does a floating dock last on the ICW?",
             "A floating dock built to our Coastal-Grade Build Standard — #1 marine-grade lumber, stainless steel fasteners, USA-made float pontoons — lasts 25–30+ years with normal maintenance. Decking is the first item that needs replacement, typically at the 12–15 year mark for pressure-treated and 30+ for IPE."),
            ("Can you replace just the float pontoons on my existing dock?",
             "Yes. If your frame is sound, swapping float pontoons is a one-day job. We use USA-made polystyrene-filled pontoons sized to your existing frame footprint."),
            ("What’s the difference between a floating dock and a fixed pier?",
             "A floating dock rises and falls with the tide; a fixed pier sits at a single elevation on driven pilings. Floating docks suit ICW homes with 3–4 ft tide swing; fixed piers are common where draft is shallower or shoreline access is limited. We build both."),
        ],
        "related": ["pilings", "boat-lifts", "custom-docks"],
    },
    {
        "slug": "fixed-piers",
        "name": "Fixed Piers",
        "h1": "Fixed Piers That Stand Strong for Decades",
        "title": "Fixed Pier Construction in Coastal NC | Intracoastal Installs",
        "meta": "Custom fixed pier construction in Hampstead, Wilmington, and coastal NC. Pile-driven foundations, marine-grade decking, custom handrails. NC GC #100980 and 30+ years of experience.",
        "subhead": "Pile-driven fixed piers with marine-grade lumber and stainless connections — engineered to your shoreline.",
        "trust_pills": ["Pile-Driven", "Custom Handrails", "30+ Years"],
        "summary": "Pile-driven fixed piers with marine-grade framing, stainless connections, and custom handrails.",
        "problem": "Fixed piers fail at the connections, not in the deck. Sub-spec hardware lets the structure rack in storm events; under-driven pilings settle and tilt. We build piers as structures, not as walking surfaces.",
        "included": [
            "Site evaluation and shoreline survey",
            "Pile depth analysis based on substrate",
            "CAMA / local permit submission",
            "Driven pilings to engineer-recommended depth",
            "Through-bolted stringers and joists with stainless steel hardware",
            "Decking in pressure-treated, composite, or IPE",
            "Custom handrails — cable, picket, or solid balustrade",
            "Optional pier-end gazebo or covered seating",
            "LED dock lighting and marine-grade conduit (optional)",
        ],
        "process": [
            ("Site visit", "Water-level and substrate notes."),
            ("Permit-aware design", "Includes pile-driving plan."),
            ("Written estimate", "Itemized scope and timeline."),
            ("Permit submission", "CAMA Major or General as appropriate."),
            ("Pile-driving", "Our in-house crew documents driven depth per piling."),
            ("Frame, deck, railing", "Through-bolted with stainless hardware."),
        ],
        "materials": [
            "Class B / CCA pile-driven pilings rated for saltwater immersion",
            "#1 marine-grade pressure-treated stringers and joists",
            "316 stainless steel through-bolts on every connection",
            "Decking choice: pressure-treated, composite, or IPE Brazilian hardwood",
            "Cable or picket railings with stainless hardware",
        ],
        "warranty": "Workmanship guaranteed to endure normal coastal NC service conditions. Hardware and decking warranties pass through.",
        "timeline": "2–4 weeks from permit approval; longer for pier-end structures.",
        "faqs": [
            ("How deep do you drive pilings for a fixed pier?",
             "Driven depth depends on substrate and pier elevation. We typically drive pilings 8–15 ft into the substrate, with a minimum of 6 ft of penetration into firm bottom. Substrate is verified at the start of pile-driving."),
            ("Can you add a covered area or gazebo to a fixed pier?",
             "Yes. We design pier-end gazebos and covered seating areas as part of the original pier or as additions. Gazebo footings tie into the pier framing for unified structural performance."),
            ("What’s the most durable decking option for a fixed pier?",
             "IPE Brazilian hardwood is the longest-lasting (50+ years unfinished). Composite (Trex, TimberTech) is mid-tier. #1 marine-grade pressure-treated southern yellow pine is the most cost-effective and lasts 12–15+ years with normal maintenance."),
            ("Do fixed piers need permits in coastal NC?",
             "Yes — CAMA jurisdiction applies. We handle CAMA Major or General Permit submission depending on size and shoreline classification."),
        ],
        "related": ["pilings", "gazebos", "custom-docks"],
    },
    {
        "slug": "boat-lifts",
        "name": "Boat Lifts",
        "h1": "Boat Lift Installation, Repair, and Mid-Season Service",
        "title": "Boat Lift Installation & Repair in Coastal NC | Intracoastal Installs",
        "meta": "Boat lift installation, repair, and mid-season service across coastal NC. Aluminum and elevator-style lifts for sport-fishing and pontoon boats. NC GC #100980.",
        "subhead": "New installs, motor and cable replacements, and mid-season service across the coastal NC corridor.",
        "trust_pills": ["USA-Made Lifts", "30+ Years", "Mid-Season Service"],
        "summary": "Boat lift installation, repair, and seasonal service for sport-fishing and pontoon boats.",
        "problem": "Boat lifts fail at the worst time: the start of the season. Cables fray quietly, motors burn out from neglected lubrication, and bunks rot when not specced for saltwater. We service before failure and repair when it happens.",
        "included": [
            "Lift selection sized to your boat displacement",
            "Cradle and bunk customization",
            "Pile-driven anchor pilings",
            "Aluminum or stainless lift hardware",
            "Motor, cable, and pulley installation",
            "Power run with marine-grade conduit",
            "Annual mid-season inspection (cable, bunk, motor)",
            "Repair: cable replacement, motor swap, bunk replacement, switch replacement",
        ],
        "process": [
            ("Boat displacement check", "We size to wet weight + 25% safety margin."),
            ("Site visit", "Substrate and shoreline notes."),
            ("Written estimate", "Itemized scope."),
            ("Permit submission", "Combined with new dock permit when applicable."),
            ("Anchor pilings + lift install", "In-house crew."),
            ("Test cycles", "We run the lift with you onboard."),
        ],
        "materials": [
            "USA-made aluminum boat lifts",
            "Stainless steel cables sized to lifted-weight rating",
            "Sealed marine-grade motors",
            "Marine-grade pressure-treated bunks with stainless lag bolts",
        ],
        "warranty": "Manufacturer warranties on motors, cables, and lift frames pass through. Workmanship guaranteed.",
        "timeline": "1–2 weeks for new installs; 1–3 days for cable/motor/bunk replacement.",
        "faqs": [
            ("What size boat lift do I need?",
             "Boat lifts are sized to lifted-weight rating — not boat length. Add 25% safety margin to your boat’s wet weight (boat + motor + fuel + gear). We can size from your boat’s specs sheet, or we’ll come measure."),
            ("How often should I have my boat lift serviced?",
             "Once per year. We recommend mid-season inspections that include cable wear check, motor lubrication, bunk inspection, and pulley check. Cables are the #1 wear item."),
            ("My boat lift won’t lower — can you fix it the same day?",
             "Often, yes. Most lift faults are switch, fuse, or relay related and we carry spares on the truck. Cable failures take longer because we typically order matched-spec cable. Call (910) 612-6107 with your lift make/model and we’ll plan accordingly."),
            ("Can you install a lift on an existing dock?",
             "If the dock framing and pilings can support the lift’s anchor loads, yes. We evaluate the existing structure first — some docks need additional pilings driven before a lift goes in."),
        ],
        "related": ["floating-docks", "fixed-piers", "dock-repairs"],
    },
    {
        "slug": "dock-repairs",
        "name": "Dock Repairs",
        "h1": "When Your Dock Needs Attention, We Fix It Right",
        "title": "Dock Repair in Coastal NC — Floating, Fixed, Boat Lift | Intracoastal Installs",
        "meta": "Floating dock, fixed pier, piling, and boat lift repair across coastal NC. Same-week response for urgent failures. NC GC #100980 and 30+ years of marine repair experience.",
        "subhead": "Cracked decking, corroded fasteners, settled pilings, frayed lift cables — we repair what others walk away from.",
        "trust_pills": ["Same-Week Response", "All Dock Types", "Saltwater-Spec Hardware"],
        "summary": "Floating dock, fixed pier, piling, and boat lift repair with saltwater-spec replacement hardware.",
        "problem": "Most dock failures are connection failures. Stainless fasteners corrode when the wrong grade is used; pressure-treated lumber rots when economy lumber was specced; pilings settle when driven too shallow. We diagnose the root cause and rebuild to the Coastal-Grade Build Standard — not just patch the symptom.",
        "included": [
            "Decking replacement (full or partial)",
            "Joist and stringer replacement",
            "Piling re-driving or sister-piling installation",
            "Hardware swap (corroded to stainless steel)",
            "Float pontoon replacement",
            "Boat lift cable, motor, bunk repair",
            "Handrail replacement and repair",
            "Storm-damage assessment and rebuild",
        ],
        "process": [
            ("Phone triage", "We assess urgency on the call."),
            ("Site visit", "Photo documentation of the failure."),
            ("Written estimate", "Repair vs. full-rebuild laid out clearly."),
            ("Scheduling", "Days for safety issues, 1–2 weeks for standard repair."),
            ("Repair", "Saltwater-spec replacement materials."),
            ("Walk-through", "We show you what we replaced and why."),
        ],
        "materials": [
            "316 stainless steel fasteners",
            "Marine-grade pressure-treated lumber",
            "USA-made float pontoons (replacement)",
            "Decking match — pressure-treated, composite, or IPE",
        ],
        "warranty": "Repair workmanship guaranteed to endure normal coastal NC service conditions.",
        "timeline": "Safety issues: 1–3 days. Standard repairs: 1–2 weeks scheduling. Storm rebuilds: scoped per project.",
        "faqs": [
            ("My dock decking is cracked — do I need a full re-deck?",
             "Not necessarily. If the joists and stringers are sound, partial replacement of the cracked deck boards extends the life by 5–10 years. We inspect the framing first; if joists show rot, we re-frame as part of the re-deck."),
            ("How soon can you respond to a storm-damaged dock?",
             "We prioritize storm-damage calls. Site visits within 1–3 business days post-storm; repair scheduling depends on scope and material lead times."),
            ("My dock pilings are leaning — can they be repaired?",
             "Sometimes. If the lean is from substrate settle, sister-piling installation (driving new pilings alongside the leaners) restores structure. If pilings are rotten at the waterline, replacement is the right call."),
        ],
        "related": ["pilings", "floating-docks", "marine-carpentry"],
    },
    {
        "slug": "gazebos",
        "name": "Gazebos",
        "h1": "Coastal NC Gazebos Built for Sun and Storm",
        "title": "Dock & Waterfront Gazebos in Coastal NC | Intracoastal Installs",
        "meta": "Custom gazebos for docks, piers, and waterfront yards across coastal NC. Marine-grade lumber, stainless steel fasteners, hurricane-aware framing. NC GC #100980.",
        "subhead": "Pier-end and yard-side gazebos built with marine-grade lumber and storm-aware framing — for the coastal NC climate.",
        "trust_pills": ["Hurricane-Aware Framing", "Marine-Grade Lumber", "Custom Designs"],
        "summary": "Custom dock-mounted and yard-side gazebos with hurricane-aware framing and marine-grade hardware.",
        "problem": "Stock gazebo kits fail in coastal NC. Fasteners corrode in the salt air, framing isn’t rated for the sustained-wind events we get, and the proportions never match the rest of the property. We design and build gazebos as part of your waterfront, not as a kit drop.",
        "included": [
            "Custom design to match your home and dock",
            "Hurricane-aware framing and connections",
            "Roof in metal, asphalt, or cedar shake",
            "Pressure-treated or IPE flooring (for pier-end gazebos)",
            "Optional benches, ceiling fans, lighting, screening",
            "Power and conduit run (optional)",
            "Stainless steel fasteners on every connection",
        ],
        "process": [
            ("Site visit", "Design conversation on the property."),
            ("Custom sketch", "Size, roof, and finish options."),
            ("Written estimate", "Itemized scope."),
            ("Permit submission", "If structural addition triggers."),
            ("Foundation", "Footings or pier connection."),
            ("Frame, roof, finish", "Walk-through."),
        ],
        "materials": [
            "#1 marine-grade pressure-treated framing",
            "316 stainless steel through-bolts and structural fasteners",
            "Hurricane ties at every load point",
            "Roofing options chosen for coastal NC wind ratings",
        ],
        "warranty": "Workmanship guaranteed. Roof and finish warranties pass through.",
        "timeline": "2–4 weeks for standalone gazebos; 3–6 weeks integrated with new dock or pier.",
        "faqs": [
            ("Can you build a gazebo at the end of my pier?",
             "Yes. Pier-end gazebos are a specialty — we frame the gazebo into the pier structure so loads transfer cleanly to the pilings. The gazebo footprint must be planned at pier-design stage, or we re-engineer the existing pier to accept the load."),
            ("What roof options work best in coastal NC?",
             "Standing-seam metal in 26 or 24 gauge is our most-recommended roof for coastal NC — long lifespan, hurricane-rated, low maintenance. Architectural asphalt shingles work well too with the right wind-rating. Cedar shake is beautiful but needs more upkeep."),
            ("Can you screen-in a gazebo?",
             "Yes. Screened gazebos are common requests. We frame for screen panels and use stainless or aluminum screen frames to resist corrosion."),
        ],
        "related": ["fixed-piers", "custom-docks", "deck-construction"],
    },
    {
        "slug": "pilings",
        "name": "Pilings",
        "h1": "The Foundation Under Every Dock We Build",
        "title": "Dock Piling Installation & Replacement in Coastal NC | Intracoastal Installs",
        "meta": "Dock piling installation and replacement across coastal NC. Pile-driven to engineer-recommended depth with treated lumber rated for saltwater immersion. NC GC #100980.",
        "subhead": "New pilings, replacement pilings, and sister-pilings — driven to depth and treated for permanent saltwater immersion.",
        "trust_pills": ["Pile-Driven", "Saltwater-Rated", "30+ Years"],
        "summary": "New pilings, replacement pilings, and sister-pilings driven to engineer-recommended depth.",
        "problem": "Pilings are where docks live or die. Wrong treatment grade and they rot at the waterline. Driven too shallow and they settle within a season. Wrong diameter and they snap in storm events. We size, treat, and drive pilings as the foundation they are.",
        "included": [
            "Substrate evaluation",
            "Piling diameter sizing based on load and wind exposure",
            "CAMA / local permits as part of dock permit",
            "Pile-driving with hydraulic or vibratory hammer",
            "Documentation of driven depth per piling",
            "Sister-piling installation for failing existing structures",
        ],
        "process": [
            ("Site visit", "Substrate notes."),
            ("Pile-driving plan", "Diameter, depth, and pattern."),
            ("Written estimate", "Itemized scope."),
            ("Permit submission", "Typically as part of full dock permit."),
            ("Pile-driving", "On-site documentation of driven depth."),
            ("Documentation handoff", "You receive driven-depth records."),
        ],
        "materials": [
            "Class B / CCA-treated pilings rated for saltwater immersion",
            "Diameters 8–12 in for residential, larger for commercial",
            "Driven 8–15 ft into firm substrate, minimum 6 ft penetration",
        ],
        "warranty": "Pile-driving workmanship guaranteed; piling treatment warranty per manufacturer.",
        "timeline": "1–3 days for piling-only work; integrated with dock construction otherwise.",
        "faqs": [
            ("How long do dock pilings last on the ICW?",
             "Properly treated and driven pilings last 25–40 years on the coastal NC ICW. Failure modes are rot at the waterline (poor treatment) or settle (under-driven). Both are preventable at install."),
            ("Can you replace a single rotten piling without rebuilding the dock?",
             "Often, yes — via sister-piling. We drive a new piling alongside the rotten one and transfer load via through-bolted brackets. The rotten piling is then cut at the waterline."),
            ("What size piling do I need?",
             "Residential dock pilings are typically 8–10 in diameter for floating dock anchor pilings, 10–12 in for fixed pier load pilings, and 10–12 in for boat lift anchors. We size based on your specific load and exposure."),
        ],
        "related": ["floating-docks", "fixed-piers", "dock-repairs"],
    },
    {
        "slug": "custom-docks",
        "name": "Custom Docks",
        "h1": "Custom Dock Designs for Coastal NC Waterfront Homes",
        "title": "Custom Dock Design & Construction in Coastal NC | Intracoastal Installs",
        "meta": "Custom dock designs for high-end coastal NC waterfront homes. IPE Brazilian hardwood, copper trim, integrated lighting, custom gazebos. NC GC #100980 and 30+ years.",
        "subhead": "Custom-designed docks for high-end coastal NC homes — from IPE hardwood decking to integrated gazebos.",
        "trust_pills": ["IPE Hardwood", "Custom Design", "Luxury Finishes"],
        "summary": "Architect-grade custom docks with IPE hardwood, integrated lighting, and bespoke layouts.",
        "problem": "A high-end home deserves a high-end dock. Builders who treat custom docks as standard-dock-with-fancy-decking miss what makes them work: proportions, transitions, hardware finish, and integration with the architecture of the home.",
        "included": [
            "Architectural-quality design conversation",
            "Custom layouts: T-head, L-head, multi-level, integrated gazebo",
            "IPE Brazilian hardwood, mahogany, or composite decking",
            "Hidden fasteners or copper-plate hardware finishes (where requested)",
            "Integrated LED lighting (deck-edge, post-cap, underwater)",
            "Custom handrails: cable, glass, picket",
            "Integrated boat lifts and dinghy launches",
            "Power, water, and dockside outlets",
        ],
        "process": [
            ("Design consultation", "On your property."),
            ("Custom sketches", "Plus material samples."),
            ("Written estimate", "Itemized line items."),
            ("Permit submission", "We file."),
            ("Construction", "In-house crew."),
            ("Final walk-through", "With documentation."),
        ],
        "materials": [
            "IPE Brazilian hardwood — 50+ year unfinished service life",
            "316 stainless steel through-bolts; copper-finish hardware available",
            "USA-made polystyrene-filled float pontoons (for floating sections)",
            "Marine-grade pressure-treated framing concealed by finish-grade decking",
        ],
        "warranty": "Workmanship guaranteed. Material warranties pass through.",
        "timeline": "4–12 weeks depending on scope, materials, and permit cycle.",
        "faqs": [
            ("What’s the difference between a custom dock and a standard floating dock?",
             "Standard floating docks use catalog dimensions, pressure-treated decking, and stock hardware. Custom docks are designed to your home and shoreline — non-standard footprints, premium materials (IPE, mahogany), integrated lighting, and finish-grade hardware."),
            ("Can you match my home’s architectural style?",
             "Yes. We coordinate with your architect or design from photos of your home. Common matches include trim profiles, paint colors, lighting fixtures, and roof material on integrated gazebos."),
            ("How long does an IPE hardwood dock last?",
             "Untreated IPE has a service life of 50+ years on the coastal NC ICW. It silvers naturally without sealer; with periodic UV-stabilizer oil it retains its rich brown."),
        ],
        "related": ["floating-docks", "gazebos", "waterfront-decks"],
    },
    {
        "slug": "deck-construction",
        "name": "Deck Construction",
        "h1": "Coastal Decks Engineered for Salt Air",
        "title": "Coastal NC Deck Construction | Intracoastal Installs",
        "meta": "Coastal NC residential deck construction with marine-grade framing and stainless fasteners. Pressure-treated, composite, and IPE decking. NC GC #100980.",
        "subhead": "Backyard decks, second-story decks, and pool decks — built to coastal NC salt-air spec.",
        "trust_pills": ["Marine-Grade Framing", "Stainless Hardware", "30+ Years"],
        "summary": "Residential decks built to coastal-NC salt-air spec with stainless fasteners and marine-grade framing.",
        "problem": "Inland deck builders bring inland habits to the coast. Galvanized fasteners corrode within a few seasons in salt air; standard pressure-treated framing rots when it shouldn’t because of the wrong treatment grade. We build decks like docks — to last.",
        "included": [
            "Site evaluation and grading notes",
            "Custom design",
            "Permit submission with local jurisdiction",
            "Footings and posts to engineer-recommended depth",
            "Marine-grade pressure-treated framing",
            "Decking choice: pressure-treated, composite, or IPE",
            "Stainless steel fasteners",
            "Custom railings and stairs",
            "Optional pergola, screened area, or built-in seating",
        ],
        "process": [
            ("Site visit", "Conversation on the property."),
            ("Sketch", "Size, layout, materials."),
            ("Written estimate", "Itemized."),
            ("Permit submission", "Local jurisdiction."),
            ("Construction", "In-house crew."),
            ("Final walk-through", "Documentation."),
        ],
        "materials": [
            "#1 marine-grade pressure-treated framing",
            "316 stainless steel structural fasteners",
            "Decking: pressure-treated, Trex / TimberTech composite, or IPE",
            "Hidden-fastener systems available",
        ],
        "warranty": "Workmanship guaranteed. Material warranties pass through.",
        "timeline": "2–5 weeks depending on scope and permit cycle.",
        "faqs": [
            ("How is a coastal deck different from an inland deck?",
             "Coastal decks face accelerated corrosion. We use 316 stainless steel fasteners (not zinc-plated, not galvanized for connections), marine-grade pressure-treated framing, and decking rated for UV and salt exposure. Connections are the #1 differentiator."),
            ("Do you handle deck permits?",
             "Yes. We submit permits with the local jurisdiction (County or Town) and coordinate inspections."),
            ("What decking material lasts longest in coastal NC?",
             "IPE Brazilian hardwood lasts longest unfinished. High-quality composite (Trex Transcend, TimberTech Advanced PVC) is comparable with no finishing. Pressure-treated is the most cost-effective and lasts 12–15 years with maintenance."),
        ],
        "related": ["waterfront-decks", "gazebos", "marine-carpentry"],
    },
    {
        "slug": "waterfront-decks",
        "name": "Waterfront Decks",
        "h1": "Waterfront Decks That Transition Beautifully to the Water",
        "title": "Waterfront Decks & Deck-to-Dock Transitions in Coastal NC | Intracoastal Installs",
        "meta": "Waterfront decks with multi-level designs, integrated stairs, and seamless deck-to-dock transitions across coastal NC. Marine-grade construction. NC GC #100980.",
        "subhead": "Multi-level waterfront decks with integrated stairs and seamless transitions to your dock or shoreline.",
        "trust_pills": ["Multi-Level Design", "Dock Integration", "Marine-Grade"],
        "summary": "Multi-level waterfront decks with integrated stairs and seamless transitions to the dock.",
        "problem": "A waterfront deck that doesn’t connect to the water disappoints. Bad designs leave a clumsy step-down, mismatched railings, and an awkward transition to the dock. Good designs flow from house to deck to dock as one structure.",
        "included": [
            "Architectural-quality design including elevations",
            "Multi-level layouts to match grade and architecture",
            "Integrated stair runs",
            "Deck-to-dock transition platforms",
            "Marine-grade framing and stainless hardware",
            "Decking match across deck and dock for visual continuity",
            "Custom railings sized for sightlines",
            "Lighting and power",
        ],
        "process": [
            ("Whole-property design", "We talk through the architecture."),
            ("Sketches", "Elevations and material options."),
            ("Coordinated permit submission", "With dock permit if combined."),
            ("Construction", "In phases or as one project."),
            ("Walk-through", "Documentation."),
        ],
        "materials": [
            "Decking matched between deck and dock for continuity",
            "Marine-grade pressure-treated framing throughout",
            "316 stainless steel structural fasteners",
            "Cable, glass, or picket railings",
        ],
        "warranty": "Workmanship guaranteed.",
        "timeline": "4–8 weeks for combined deck-and-dock projects.",
        "faqs": [
            ("Can you build the deck and dock as one project?",
             "Yes — that’s our preferred approach. Coordinated design lets us match decking, railings, and lighting across the whole structure, and we permit and build in one cycle."),
            ("How do you handle the transition from deck to floating dock?",
             "An articulating gangway is the standard transition. We build it with handrails sized to match the deck railing and decking that matches the deck."),
        ],
        "related": ["deck-construction", "custom-docks", "floating-docks"],
    },
    {
        "slug": "marine-carpentry",
        "name": "Marine Carpentry",
        "h1": "Marine Carpentry From Bulkheads to Boathouses",
        "title": "Marine Carpentry: Bulkheads, Boathouses, Sea Walls in Coastal NC | Intracoastal Installs",
        "meta": "Marine carpentry across coastal NC: bulkhead construction and repair, boathouses, sea walls, and specialty marine joinery. NC GC #100980 and 30+ years of waterfront experience.",
        "subhead": "Bulkheads, sea walls, boathouses, and specialty marine joinery — the work that keeps coastal NC waterfronts intact.",
        "trust_pills": ["Bulkheads", "Boathouses", "Sea Walls"],
        "summary": "Bulkhead, sea wall, boathouse, and specialty marine joinery work across coastal NC.",
        "problem": "Marine carpentry is its own discipline. Bulkheads fail at the deadman; sea walls fail at the toe; boathouses fail at the eave-to-frame connection. We’ve spent 30+ years learning where these structures fail and how to build them so they don’t.",
        "included": [
            "Bulkhead construction and repair",
            "Sea wall construction",
            "Boathouse framing and roofing",
            "Specialty joinery (custom benches, integrated planters, custom storage)",
            "Permit submission for shoreline structures",
        ],
        "process": [
            ("Site evaluation", "Shoreline survey."),
            ("Permit-aware design", "Sketch with structure."),
            ("Written estimate", "Itemized."),
            ("Permit submission", "CAMA Major typical for bulkheads."),
            ("Construction", "In-house crew."),
            ("Walk-through", "Documentation."),
        ],
        "materials": [
            "Treated timber bulkhead boards or vinyl bulkhead sheets",
            "Tieback rods to engineer-recommended deadman depth",
            "316 stainless steel fasteners on all connections",
            "Marine-grade lumber for boathouse framing with hurricane connectors",
        ],
        "warranty": "Workmanship guaranteed.",
        "timeline": "Bulkheads: 1–3 weeks. Boathouses: 4–8 weeks. Sea walls: project-dependent.",
        "faqs": [
            ("How long does a bulkhead last on the ICW?",
             "Treated timber bulkheads last 20–30 years; vinyl bulkheads 30–50 years. Failure modes are tieback corrosion (preventable with stainless rods) and toe scour (preventable with riprap toe)."),
            ("Can you build a boathouse over my existing dock?",
             "If the dock framing and pilings can support the boathouse load, yes. Most existing docks need additional pilings driven to anchor the boathouse roof load."),
            ("What permits do bulkheads require in coastal NC?",
             "CAMA Major Permit is typical for new bulkheads or extensions. Repair and maintenance often qualify for General Permits. We handle the submission."),
        ],
        "related": ["pilings", "fixed-piers", "dock-repairs"],
    },
]

CITIES = [
    {
        "slug": "hampstead-nc",
        "name": "Hampstead, NC",
        "short": "Hampstead",
        "county": "Pender County",
        "h1": "Hampstead Docks From Our Olde Point HQ",
        "title": "Dock Builder in Hampstead, NC | Intracoastal Installs",
        "meta": "Family-owned dock builder headquartered at 312 Olde Point Loop in Hampstead, NC. Floating docks, fixed piers, boat lifts, and gazebos for Pender County waterfronts. NC GC #100980.",
        "subhead": "We’re based at 312 Olde Point Loop — Hampstead’s dock work is our home turf.",
        "trust_pills": ["HQ in Hampstead", "Pender County", "30+ Years"],
        "summary": "Our HQ city. Floating docks, piers, lifts across Pender County waterfronts.",
        "lat": 34.3683, "lng": -77.7102,
        "local_hooks": [
            "Olde Point neighborhood — mature waterfront homes on the Intracoastal Waterway with sound-side docks",
            "Tide swings on the Topsail Sound side run 3–4 ft — floating docks with adequate piling height are essential",
            "Hampstead’s proximity to Topsail Inlet means harder wind/wave exposure on the ICW than upstream stretches",
            "Pender County permits move through CAMA + local jurisdiction; we handle the full submission",
        ],
        "featured_services": ["floating-docks", "fixed-piers", "boat-lifts", "dock-repairs", "pilings"],
        "adjacent": ["wilmington-nc", "surf-city-nc", "topsail-beach-nc"],
        "faqs": [
            ("Where in Hampstead are you based?",
             "Our headquarters is at 312 Olde Point Loop, Hampstead, NC 28443 — in the Olde Point community on the Topsail Sound side of Hampstead. Most of our crew lives within a 15-mile radius."),
            ("Do you serve all of Pender County?",
             "We work the coastal Pender County waterfront from Hampstead north to the Onslow County line. For inland Pender requests, call (910) 612-6107 to confirm coverage."),
            ("What’s the typical tide swing on the Hampstead ICW?",
             "Hampstead’s Intracoastal Waterway frontage sees 3–4 ft tide swings on a normal-cycle day, more on full-moon spring tides. Floating docks in Hampstead need adequate piling height and gangway length to handle that swing."),
            ("Do I need a CAMA permit for a Hampstead dock?",
             "Almost always, yes. CAMA Major or General Permit jurisdiction depends on size and water-frontage classification. We handle the submission as part of our process."),
        ],
    },
    {
        "slug": "wilmington-nc",
        "name": "Wilmington, NC",
        "short": "Wilmington",
        "county": "New Hanover County",
        "h1": "Cape Fear & ICW Docks for Wilmington Homeowners",
        "title": "Dock Builder in Wilmington, NC | Intracoastal Installs",
        "meta": "Floating docks, fixed piers, boat lifts, and gazebos for Wilmington, NC waterfronts. Cape Fear River and ICW expertise. NC GC #100980 and 30+ years on coastal NC.",
        "subhead": "Cape Fear River and ICW-side dock construction across New Hanover County.",
        "trust_pills": ["Cape Fear & ICW", "New Hanover County", "30+ Years"],
        "summary": "Cape Fear River and ICW-side dock construction for New Hanover County homeowners.",
        "lat": 34.2257, "lng": -77.9447,
        "local_hooks": [
            "Cape Fear River waterfront vs. ICW-side — different piling and decking requirements between the two",
            "Historic Wilmington homes (Forest Hills, Pine Valley) often need dock retrofits matching original architecture",
            "New Hanover County permitting and CAMA Major vs. General permits depend on water-frontage type",
            "Salt-air corrosion is more severe in downtown Wilmington than inland New Hanover — stainless steel fasteners are essential",
        ],
        "featured_services": ["floating-docks", "fixed-piers", "boat-lifts", "dock-repairs", "custom-docks", "marine-carpentry"],
        "adjacent": ["wrightsville-beach-nc", "carolina-beach-nc", "hampstead-nc"],
        "faqs": [
            ("Do you build on the Cape Fear River side of Wilmington?",
             "Yes. The Cape Fear waterfront has different current and substrate conditions than the ICW — we spec piling depth and dock anchorage accordingly."),
            ("How does CAMA differ on the river vs. the ICW in Wilmington?",
             "CAMA Major Permit jurisdiction often applies on Cape Fear waterfronts due to the federal navigable channel and Army Corps interest; the ICW side typically uses CAMA Major or General depending on size. We file the right paperwork either way."),
            ("Can you retrofit a dock to match a historic Wilmington home?",
             "Yes. We’ve done dock work for Forest Hills, Pine Valley, and historic downtown homes — matching trim profiles, paint colors, and lighting fixtures to the home’s architecture."),
        ],
    },
    {
        "slug": "topsail-beach-nc",
        "name": "Topsail Beach, NC",
        "short": "Topsail Beach",
        "county": "Pender County",
        "h1": "Hurricane-Rated Docks for Topsail Beach",
        "title": "Dock Builder in Topsail Beach, NC | Intracoastal Installs",
        "meta": "Hurricane-rated dock construction for Topsail Beach, NC sound-side homes. Heavier piling, marine-grade lumber, stainless steel fasteners. NC GC #100980.",
        "subhead": "Sound-side floating docks and fixed piers built for Topsail Beach’s hurricane exposure.",
        "trust_pills": ["Hurricane-Rated", "Sound-Side Specialists", "Pender County"],
        "summary": "Sound-side floating docks and fixed piers built to handle Topsail Beach hurricane exposure.",
        "lat": 34.3793, "lng": -77.6235,
        "local_hooks": [
            "Sound-side homes only — ocean-side homes don’t get dock construction; we build along the ICW and Topsail Sound",
            "Topsail Sound shallow draft means careful piling depth surveys before installation",
            "Hurricane-rated construction is non-negotiable on Topsail — we use heavier pile diameter and additional cross-bracing",
            "Pender County / Town of Topsail Beach dual permits for floating docks",
        ],
        "featured_services": ["floating-docks", "fixed-piers", "pilings", "dock-repairs", "gazebos"],
        "adjacent": ["surf-city-nc", "hampstead-nc"],
        "faqs": [
            ("Do you only build on the sound side of Topsail Beach?",
             "Yes — ocean-side properties don’t have dock construction. We build along the ICW and Topsail Sound waterfronts."),
            ("How do you handle hurricane exposure on Topsail Beach?",
             "Heavier pile diameter, additional cross-bracing, hurricane-rated connectors at every load point, and stainless steel fasteners that don’t fail in surge events. We build to the upper end of code."),
            ("Do I need both Pender County and Town of Topsail Beach permits?",
             "Often yes — CAMA + Pender + Town. We handle the concurrent submission."),
        ],
    },
    {
        "slug": "wrightsville-beach-nc",
        "name": "Wrightsville Beach, NC",
        "short": "Wrightsville Beach",
        "county": "New Hanover County",
        "h1": "Wrightsville Sound & Banks Channel Docks",
        "title": "Dock Builder in Wrightsville Beach, NC | Intracoastal Installs",
        "meta": "Wrightsville Sound and Banks Channel dock construction. Floating docks, fixed piers, boat lifts for Harbor Island and the south end. NC GC #100980.",
        "subhead": "Wrightsville Sound and Banks Channel dock construction for Harbor Island, the north end, and the south end.",
        "trust_pills": ["Banks Channel", "Tidal Current Spec", "New Hanover County"],
        "summary": "Wrightsville Sound and Banks Channel dock construction with current-spec anchorage.",
        "lat": 34.2085, "lng": -77.7962,
        "local_hooks": [
            "Wrightsville Sound and Banks Channel are the primary waterways — both have strong tidal currents that require floating dock anchorage redesign",
            "Lee’s Cut and Motts Channel access — specific permit considerations for boat-lift installation",
            "Tightly-spaced waterfront lots in Harbor Island and the south end mean precision dock layout matters",
            "New Hanover County + Town of Wrightsville Beach concurrent permits",
        ],
        "featured_services": ["floating-docks", "boat-lifts", "custom-docks", "dock-repairs", "waterfront-decks"],
        "adjacent": ["wilmington-nc", "carolina-beach-nc", "figure-eight-island-nc"],
        "faqs": [
            ("How do strong currents in Banks Channel affect dock design?",
             "Strong tidal currents require heavier anchorage on floating docks, deeper piling drive, and articulating gangways with extra throw to handle current-driven sway."),
            ("Can you fit a dock on a tight Harbor Island lot?",
             "Yes — precision layout is part of the design conversation. We measure waterfront width, neighbor setbacks, and waterway clearance before committing to a footprint."),
            ("Do Wrightsville Beach docks need both Town and County permits?",
             "Yes — CAMA + New Hanover + Town of Wrightsville Beach. We file all three."),
        ],
    },
    {
        "slug": "carolina-beach-nc",
        "name": "Carolina Beach, NC",
        "short": "Carolina Beach",
        "county": "New Hanover County",
        "h1": "Carolina Beach Docks Built for Tide and Wind",
        "title": "Dock Builder in Carolina Beach, NC | Intracoastal Installs",
        "meta": "Carolina Beach Yacht Basin and Snow’s Cut dock construction. Boat lifts for sport-fishing boats. Hurricane-aware framing. NC GC #100980.",
        "subhead": "Yacht Basin and Snow’s Cut dock construction with boat lifts sized for offshore-capable boats.",
        "trust_pills": ["Yacht Basin", "Sport-Fishing Lifts", "Hurricane-Aware"],
        "summary": "Yacht Basin and Snow’s Cut dock construction with sport-fishing boat lift expertise.",
        "lat": 34.0357, "lng": -77.8936,
        "local_hooks": [
            "Carolina Beach Yacht Basin and Snow’s Cut waterfront homes are our primary work areas",
            "Pleasure Island wind exposure means added bracing on fixed piers",
            "Boat lift demand is high here for sport-fishing and offshore-capable boats",
            "New Hanover County + Town of Carolina Beach concurrent permits",
        ],
        "featured_services": ["floating-docks", "boat-lifts", "fixed-piers", "pilings", "dock-repairs"],
        "adjacent": ["wilmington-nc", "wrightsville-beach-nc"],
        "faqs": [
            ("Do you install boat lifts for sport-fishing boats in Carolina Beach?",
             "Yes — sport-fishing lifts are common in the Yacht Basin and along Snow’s Cut. We size to lifted weight (boat + motor + fuel + gear with 25% safety margin)."),
            ("How do you account for Pleasure Island wind exposure?",
             "Additional cross-bracing on fixed piers, hurricane-rated connectors at every load point, and heavier piling diameter on exposed lots."),
        ],
    },
    {
        "slug": "figure-eight-island-nc",
        "name": "Figure Eight Island, NC",
        "short": "Figure Eight Island",
        "county": "New Hanover County",
        "h1": "Figure Eight Island Waterfront Construction",
        "title": "Dock Builder for Figure Eight Island, NC | Intracoastal Installs",
        "meta": "Custom dock and waterfront construction for Figure Eight Island, NC. IPE hardwood, copper-finish hardware, custom gazebos. NC GC #100980.",
        "subhead": "Custom dock and waterfront construction for Figure Eight Island residences — IPE hardwood, copper-finish hardware, custom gazebos.",
        "trust_pills": ["Private Island Access", "IPE Hardwood", "Custom Designs"],
        "summary": "Custom dock and waterfront construction for Figure Eight Island private-island residences.",
        "lat": 34.2705, "lng": -77.7400,
        "local_hooks": [
            "Private island access means our crews coordinate scheduling with the gatehouse and homeowners",
            "Banks Channel and Nixon Channel exposure varies by lot — design accounts for wave-state on each side",
            "High-end residential market means specialty materials (IPE Brazilian hardwood, copper trim, custom gazebos)",
            "New Hanover County permitting + private island association coordination",
        ],
        "featured_services": ["custom-docks", "floating-docks", "gazebos", "waterfront-decks", "boat-lifts"],
        "adjacent": ["wrightsville-beach-nc", "wilmington-nc"],
        "faqs": [
            ("How do you coordinate access to Figure Eight Island?",
             "We schedule deliveries and crew arrivals through the gatehouse and the homeowner. Materials are staged to minimize trips across the bridge."),
            ("Do you build with IPE on Figure Eight Island?",
             "Yes — IPE Brazilian hardwood is one of our most-requested materials on Figure Eight, paired with copper-finish hardware and custom gazebos."),
        ],
    },
    {
        "slug": "surf-city-nc",
        "name": "Surf City, NC",
        "short": "Surf City",
        "county": "Pender / Onslow County",
        "h1": "Topsail Sound & Stump Sound Docks for Surf City",
        "title": "Dock Builder in Surf City, NC | Intracoastal Installs",
        "meta": "Sound-side floating docks and fixed piers in Surf City, NC. Topsail Sound and Stump Sound expertise. Pender and Onslow County permitting. NC GC #100980.",
        "subhead": "Topsail Sound and Stump Sound floating docks and fixed piers across Surf City’s sound-side waterfronts.",
        "trust_pills": ["Sound-Side", "Hurricane-Rated", "Pender / Onslow"],
        "summary": "Topsail Sound and Stump Sound dock construction across Surf City sound-side homes.",
        "lat": 34.4263, "lng": -77.5450,
        "local_hooks": [
            "Sound-side homes along Topsail Sound and Stump Sound — floating dock construction predominates",
            "Surf City Bridge area has shallower draft — piling depth surveys are essential",
            "Pender / Onslow county boundary — we’ve handled permits in both jurisdictions",
            "Hurricane Florence (2018) reconstruction work in Surf City informs how we spec dock attachments today",
        ],
        "featured_services": ["floating-docks", "fixed-piers", "pilings", "dock-repairs", "boat-lifts"],
        "adjacent": ["topsail-beach-nc", "hampstead-nc", "sneads-ferry-nc"],
        "faqs": [
            ("Are you familiar with both Pender and Onslow County permits?",
             "Yes — the Pender/Onslow line runs through Surf City, and we’ve filed in both. We’ll route your permit to the right county based on your address."),
            ("How does the Surf City Bridge area affect dock design?",
             "Shallower draft near the bridge means careful piling depth surveys; boat lifts may need elevated bunks, and floating dock anchor pilings need depth sufficient to clear minimum-tide draft."),
        ],
    },
    {
        "slug": "sneads-ferry-nc",
        "name": "Sneads Ferry, NC",
        "short": "Sneads Ferry",
        "county": "Onslow County",
        "h1": "New River & Mile Hammock Bay Dock Builds",
        "title": "Dock Builder in Sneads Ferry, NC | Intracoastal Installs",
        "meta": "New River and Mile Hammock Bay dock construction in Sneads Ferry, NC. Working-dock requirements for the commercial-fishing community. NC GC #100980.",
        "subhead": "New River and Mile Hammock Bay residential and small-commercial dock construction.",
        "trust_pills": ["New River", "Onslow County", "Working Docks"],
        "summary": "New River and Mile Hammock Bay residential and small-commercial dock construction.",
        "lat": 34.5530, "lng": -77.3905,
        "local_hooks": [
            "New River and Mile Hammock Bay waterfront — commercial fishing community with working-dock requirements",
            "Onslow County permitting; Coastal Resources Commission rules apply on the New River side",
            "Strong currents through the Sneads Ferry inlet require extra piling depth and stainless cross-bracing",
            "We handle both residential and small commercial dock builds in Sneads Ferry",
        ],
        "featured_services": ["floating-docks", "fixed-piers", "pilings", "boat-lifts", "marine-carpentry"],
        "adjacent": ["surf-city-nc", "topsail-beach-nc"],
        "faqs": [
            ("Do you build commercial-grade docks in Sneads Ferry?",
             "Yes — we handle small-commercial working docks with heavier piling, reinforced framing, and saltwater-spec hardware suited to the fishing community’s daily-use loads."),
            ("How do strong currents at the Sneads Ferry inlet affect design?",
             "Extra piling depth, stainless steel cross-bracing, and articulating gangways with extra throw to handle current-driven sway."),
        ],
    },
]

HOMEPAGE_FAQS = [
    ("What areas of coastal North Carolina do you serve?",
     "We build and repair docks, piers, boat lifts, and gazebos across Hampstead, Wilmington, Topsail Beach, Wrightsville Beach, Carolina Beach, Figure Eight Island, Surf City, and Sneads Ferry, NC. Our headquarters is at 312 Olde Point Loop, Hampstead, NC 28443. Call (910) 612-6107 to confirm we cover your address."),
    ("Are you licensed and insured in North Carolina?",
     "Yes. We hold North Carolina General Contractor License #100980 and carry full liability insurance. License and insurance documentation is available on request before any project starts."),
    ("How much does a floating dock cost in coastal NC?",
     "Floating dock pricing varies based on size, decking material (pressure-treated, composite, or IPE Brazilian hardwood), permit complexity, and site conditions. We provide free written estimates after a site evaluation — call (910) 612-6107 or use the contact form to schedule yours."),
    ("Do you handle dock permits?",
     "Yes. Permit consultation is part of our process. We coordinate with CAMA (NC Coastal Area Management Act), local jurisdictions, and Army Corps of Engineers requirements where applicable for floating docks, fixed piers, and pilings."),
    ("What materials do you use on your docks?",
     "We exclusively use #1 marine-grade pressure-treated lumber, top-quality commercial-grade hardware, and stainless steel fasteners on every dock we build. Decking options include pressure-treated, composite, and IPE Brazilian hardwood. We represent only USA-made brands."),
    ("How long does a floating dock installation take?",
     "Most floating dock installations take 1–3 weeks from permit approval through final inspection, depending on size and site conditions. Repairs can often be completed in 1–3 days. We confirm timeline with each written estimate."),
    ("Do you offer dock repair as well as new installation?",
     "Yes. We repair floating docks, fixed piers, boat lifts, and pilings — from simple board replacements to full re-decking and structural repair. See our dock repair services for details."),
]

CONTACT_FAQS = [
    ("How quickly do you respond?",
     "Within 1 business day, Monday–Friday 7am–5pm. Storm-damage and safety calls get priority routing."),
    ("Are estimates free?",
     "Yes. Site visits and written estimates are free, with no obligation. We won’t pressure you and we won’t add hidden charges later."),
    ("What information do I need to provide?",
     "Your address, the type of project (new dock, repair, lift, etc.), and a rough timeline. Photos help. Don’t worry about technical details — we cover those at the site visit."),
    ("Do you come to my home for estimates?",
     "Yes. We don’t quote off photos or maps for new construction — we visit, measure tide, check substrate, and walk the property with you."),
]
